name: Shining Light
favicon: null
layout_spectrum: 0.3887396117206663
typography_spectrum: 0.5462005266454071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6081992376130074
  lightness: 0.5134107556659728
  saturation: 0.47692124103195965
  rhythmicContrast: 0.7826600724365562
purpose: []
